name: Build Dumper

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build App
        # This forces the output into a specific folder we can find easily
        run: msbuild Il2CppRuntimeDumper.sln /p:Configuration=Release /p:Platform=x64 /p:OutDir=C:\build_output\

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Il2CppDumper-Binary
          # Now we point exactly to where we told MSBuild to put it
          path: C:\build_output\Il2CppRuntimeDumper.exe
