name: Build Dumper

on: [workflow_dispatch] # Allows you to run it manually

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build App
        run: msbuild Il2CppRuntimeDumper.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Il2CppDumper-Binary
          path: x64/Release/Il2CppRuntimeDumper.exe
